sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
  - hexo deploy
deploy:
  provider: git
  repo: https://gigaSproule:${GH_TOKEN}@github.com/gigaSproule/gigasproule.github.io
  branch: master
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true

