version: 2.3.0
favicon:
rss:
logo:
  text: ' '
open_graph:
  fb_app_id:
  fb_admins:
  twitter_id:
  twitter_site:
  google_plus:
navbar:
  menu:
    Home: /
    About: /about
    Experience: /experience
  links:
footer:
  links:
article:
  # Code highlight theme - https://github.com/highlightjs/highlight.js/tree/master/src/styles
  highlight: atom-one-light
  thumbnail: true
  readtime: true
search:
  type: insight
comment:
  type: disqus
  shortname: benjaminsproulecom
donate:
share:
  type:
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - type: profile
    position: right
    author: Benjamin Sproule
    author_title: Software Developer
    location: Reading, United Kingdom
    avatar:
    gravatar: benjamin@benjaminsproule.com
    avatar_rounded: false
    follow_link: 'https://github.com/gigaSproule'
    social_links:
      Facebook:
        icon: fab fa-facebook
        url: 'https://facebook.com/benjaminsproule'
      Github:
        icon: fab fa-github
        url: 'https://github.com/gigaSproule'
      LinkedIn:
        icon: fab fa-linkedin
        url: 'https://uk.linkedin.com/pub/benjamin-sproule/50/744/754'
      Twitter:
        icon: fab fa-twitter
        url: 'https://twitter.com/gigaSproule'
  - type: archive
    position: right
  - type: category
    position: right
  - type: tag
    position: right
plugins:
  animejs: true
  outdated-browser: true
  back-to-top: true
  progressbar: true
  clipboard: true
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
