# Header
menu:
  Home: /
  Archives: /archives
  Experience: /experience
  Technical Skills: /technical-skills
  Non-Technical Skills: /non-technical-skills

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # whether to show profile bar
gravatar: true # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  facebook: http://facebook.com/benjaminsproule
  github: http://github.com/gigaSproule
  google-plus: http://plus.google.com/+BenjaminSproule
  linkedin: http://uk.linkedin.com/pub/benjamin-sproule/50/744/754
  twitter: http://twitter.com/gigaSproule

about: I'm a software developer who likes to tweak/break gadgets and complain about everything under the sun. When I'm not doing that, I'm usually playing games, watching films or watching sports.

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
email: benjamin@benjaminsproule.com
