# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Experience: /experience
  Technical Skills: /technical-skills
  Non-Technical Skills: /non-technical-skills

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # whether to show profile bar

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  facebook: http://facebook.com/benjaminsproule
  github: http://github.com/gigaSproule
  google-plus: http://plus.google.com/+BenjaminSproule
  linkedin: http://uk.linkedin.com/pub/benjamin-sproule/50/744/754
  twitter: http://twitter.com/gigaSproule

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
email: benjamin@benjaminsproule.com
